name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter github branch name to be deployed'
        required: true
        default: 'main'
      description:
        description: 'Enter description about deployment'
        required: true
        default: 'New feature release'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-west1 
  GKE_CLUSTER: plg
  GKE_ZONE: us-west1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - uses: actions/checkout@v2
      with:
        repository: "WhisperChain/dev.secrets"
        ref: "main"
        token: ${{ secrets.PAT }}
        path: "secrets"
        
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and generate static page
      run: |-
        mv secrets/frontend.prod.env .env.local
        sudo apt install -y curl
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt install -y nodejs
        npm install
        npx next build
        npx next export
        
    - id: 'upload-folder'
      env:	
        BUCKET_NAME: "whisperchain-frontend"
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'out/'
        destination: $BUCKET_NAME
        
    - id: 'upload-file'
      env:	
        BUCKET_NAME: "whisperchain-frontend"
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'out/'
        destination: $BUCKET_NAME
